import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {migrateDocument,commitDocument} from '../model/document';
import {previewDocument} from '../model/previewDocument';
const mocks=vi.hoisted(()=>({load:vi.fn(),read:vi.fn(),save:vi.fn(),draw:vi.fn()}));
vi.mock('../utils',()=>({loadData:mocks.load,resolveDataCategory:async()=> 'basic_charts'}));
vi.mock('@/services/dsl',()=>({loadDSLFile:mocks.read,saveDSLFile:mocks.save,usesLocalDSLService:true}));
vi.mock('../model/Chart',()=>({visualChart:{setRandomGenerator:vi.fn(),reset:vi.fn(),parseDSL:vi.fn(),restoreViewSnapshot:vi.fn(),drawData:mocks.draw,initSVGDOM:vi.fn()}}));
vi.mock('../../D3Chart',()=>({D3Chart:()=> <svg/>}));
vi.mock('../model/editor', () => ({prepareDocumentEdit: (_current: unknown, next: unknown) => migrateDocument(next), validateRenderableDocument: (next: unknown) => migrateDocument(next)}));
import {Gallery} from './Gallery';
const fixture=()=>migrateDocument(JSON.parse(readFileSync('src/datav3/basic_charts/01_simple_bar_chart.json','utf8')));
afterEach(()=>{cleanup();vi.clearAllMocks();vi.unstubAllGlobals();});
it('ignores a slow previous selection and mounts the large text editor only on demand',async()=>{
 let first!:(v:unknown)=>void;
 mocks.load.mockImplementation((name:string)=>name==='01_simple_bar_chart'?new Promise(resolve=>{first=resolve}):Promise.resolve({...fixture(),description:'Latest selection'}));
 render(<Gallery/>);
 expect(screen.queryByRole('textbox')).toBeNull();
 fireEvent.click(screen.getAllByAltText('02 radial bar chart')[0]);
 await waitFor(()=>expect(mocks.draw).toHaveBeenCalledTimes(1));
 await act(async()=>first({...fixture(),description:'Stale selection'}));
 expect(mocks.draw).toHaveBeenCalledTimes(1);
 fireEvent.click(screen.getByText('Show JSON'));
 expect((screen.getByRole('textbox') as HTMLTextAreaElement).value).toContain('Latest selection');
});
it('preserves the full source history when saving a compact preview',async()=>{
 const base=fixture();base.history={cursor:0,entries:[]};
 const full=commitDocument(base,{...base,description:'Existing edit'},{source:'json'}).document;
 mocks.load.mockResolvedValue(previewDocument(full));mocks.read.mockResolvedValue({content:full,hash:'existing'});mocks.save.mockResolvedValue({success:true});vi.stubGlobal('alert',vi.fn());
 render(<Gallery/>);await waitFor(()=>expect(mocks.draw).toHaveBeenCalledTimes(1));
 fireEvent.click(screen.getByText('Show JSON'));
 const edited={...previewDocument(full),description:'New edit'};
 fireEvent.change(screen.getByRole('textbox'),{target:{value:JSON.stringify(edited)}});
 await waitFor(()=>expect(mocks.draw).toHaveBeenCalledTimes(2));
 fireEvent.click(screen.getByText('Save'));
 await waitFor(()=>expect(mocks.save).toHaveBeenCalledTimes(1));
 const saved=mocks.save.mock.calls[0][2];
 expect(saved.history.entries).toHaveLength(2);
 expect(saved.history.entries[0]).toEqual(full.history.entries[0]);
 expect(full.history.entries).toHaveLength(1);
});
it('does not save invalid JSON when Save is clicked before the debounce finishes',async()=>{
 mocks.load.mockResolvedValue(previewDocument(fixture()));
 render(<Gallery/>);await waitFor(()=>expect(mocks.draw).toHaveBeenCalled());
 fireEvent.click(screen.getByText('Show JSON'));
 fireEvent.change(screen.getByRole('textbox'),{target:{value:'{'}});
 fireEvent.click(screen.getByText('Save'));
 await waitFor(()=>expect(screen.getByRole('alert')).toBeInTheDocument());
 expect(mocks.save).not.toHaveBeenCalled();
 expect(screen.getByText('Save')).toBeDisabled();
});
