export enum ChartFiles {
  IFOREST = 'iForest',
  OPINION_SEER = 'OpinionSeer',
  BIT_EXTRACT = 'bitextract',
  STACKED_BAR = 'stackedBar',
  STACKED_AREA = 'stackedArea',
  SIMPLE_BAR_CHART = '01__simple_bar_chart',
  RADIAL_BAR_CHART = '02__radial_bar_chart',
  STACKED_BAR_CHART = '03__Stacked_bar_chart_with_round_orner',
  RADIAL_STACKED_BAR_CHART = '04__radial_stacked_bar_chart',
  GROUPED_BAR_CHART = '05__Grouped_Bar_Chart',
  SCATTER_PLOT = '06__Scatter_plot',
  BUBBLE_PLOT_1 = '07__bubble_plot_1',
  BUBBLE_PLOT_2 = '08__bubble_plot_2',
  HISTOGRAM_SCATTERPLOT = '09__2D_Histogram_Scatterplot',
  HISTOGRAM_HEATMAP = '10__2D_Histogram_Heatmap',
  DOT_PLOT = '11__dot_plot',
  STRIP_PLOT = '12__Strip_Plot',
  PIE_CHART = '13__Pie_Chart',
  DONUT_CHART = '14__Donut_Chart',
}
